//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabel_clienti
    {
        
        public string Id { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Tip_Camera { get; set; }
        public string Check_IN { get; set; }
        public string Check_OUT { get; set; }
        public string Carte_Credit { get; set; }
        public string Numar_Carte { get; set; }
        public string Data_expirare { get; set; }
        public string CCV { get; set; }
        public string Mentiuni { get; set; }

        public Tabel_clienti() { }

        public Tabel_clienti(string id, string nume, string prenume, string tip_Camera, string check_IN, string check_OUT, string carte_Credit, string numar_Carte, string data_expirare, string cCV, string mentiuni)
        {
            Id = id;
            Nume = nume;
            Prenume = prenume;
            Tip_Camera = tip_Camera;
            Check_IN = check_IN;
            Check_OUT = check_OUT;
            Carte_Credit = carte_Credit;
            Numar_Carte = numar_Carte;
            Data_expirare = data_expirare;
            CCV = cCV;
            Mentiuni = mentiuni;
        }
    }
}
